### ISSUE TITLE
Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by GioKas93** [PixelExtended/auth#11]
### Name

GioKas93

### Additional Context

Knew about PEX back when it was still PixelExperience-FanEdition on K20p community. I would like to join to apply for Official maintainership  ;)

**Comment by iamimmanuelraj** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PixelExtended/people<br>
