### ISSUE TITLE
Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by potthead1** [PixelExtended/auth#12]
### Name

Potthead1

### Additional Context

I came to know about this PEX when i was in Realme GT master community I loved the rom since then and currently I was accepted as a mantainer for POCO X4 PRO 5G / Veux there fore i wana join the community

**Comment by iamimmanuelraj** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PixelExtended/people<br>
