### ISSUE TITLE
Add chaitanya to maintainers

### ISSUE THREAD

**Issue by Chaitanyakm** [PixelExtended/auth#14]
### Name

Chaitanya

### Additional Context

.

**Comment by iamimmanuelraj** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PixelExtended/people<br>
